name: Release CI
on:
  push:
    branches:
      - master
      - alpha
      - beta
      - rc

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Setup npm 7
        run: npm i -g npm@7 --registry=https://registry.npmjs.org

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.3.11'

      - name: Install deps
        run: bun i

      - name: Release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
